steps:
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
          - gcloud
          - functions
          - deploy
          - CoordinatesToTimezone
          - --region=us-central1
          - --trigger-http
          - --allow-unauthenticated
          - --source=build/deploy
          - --entry-point=com.jtschwartz.coordinatesToTimezone.CoordinatesToTimezone
          - --trigger-http
          - --runtime=java11