steps:
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      args:
          - gcloud
          - functions
          - deploy
          - CoordinatesToTimezone
          - --region=us-central1
          - --source=.
          - --trigger-http
          - --runtime=java11