steps:
    - name: 'gradle:7.3-jdk8'
      volumes:
          - name: 'jar'
            path: '/jar'
      entrypoint: 'gradle'
      args: ['buildFunction', '-PdeploymentPath=/jar/deploy']
      id: 'Build JAR'
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      volumes:
          - name: 'jar'
            path: '/jar'
      args:
          - gcloud
          - functions
          - deploy
          - CoordinatesToTimezone
          - --region=us-central1
          - --trigger-http
          - --allow-unauthenticated
          - --source=deploy
          - --entry-point=com.jtschwartz.coordinatesToTimezone.CoordinatesToTimezone
          - --trigger-http
          - --runtime=java11
      id: 'Deploy'