steps:
    - name: 'gradle:7.3-jdk8'
      volumes:
          - name: 'jar'
            path: '/jar'
      entrypoint: 'bash'
      args:
          - -c
          - |
              gradle buildFunction &&
              mv build/libs/*all.jar /jar
      id: 'Build JAR'
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      volumes:
          - name: 'jar'
            path: '/jar'
      args:
          - gcloud
          - functions
          - deploy
          - CoordinatesToTimezone
          - --region=us-central1
          - --trigger-http
          - --allow-unauthenticated
          - --source=/jar
          - --entry-point=com.jtschwartz.coordinatesToTimezone.CoordinatesToTimezone
          - --trigger-http
          - --runtime=java11
      id: 'Deploy'